### ISSUE TITLE
downloadRegistry not working well within nodezoo

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-dequeue#5]
I've done quite a bit of investigation on this, and few things. First there isn't one thing, if I hack one part to get it working, something else breaks. A good starting point though, is redis-queue transport.

It _seems_ as if there is no concurrency control on things coming off the queue, so they are being processed at full speed. I'm not sure if that is intended, and I opened an issue [here](https://github.com/senecajs/seneca-redis-queue-transport/issues/20)

I put a setInterval inside the downloadRegistry to throttle things a bit (for testing only), and processed 4000 records at 1package/2 sec. I was able to process about 3000 of them before I had a failure from nodezoo-service, and nodezoo-npm (which instead of capturing the logs, I started the service like a derp so now I don't know why -- I'll reproduce). 

So for now, the queue and dequeue is doing what it needs to do. However, extra steps need to be taken to stabilize the entire system.

**Comment by Georgette** [comment]
I did get this from an npm service crash:

```
2016-04-20T03:41:32.723Z ecsaefk5ju7g/1461117713977/7376/nodezoo-npm WARN   -   -   ACT 6rd9pow3bnk9/agc94j2db5qj   name:transport,plugin:define,role:seneca,seq:3,tag:undefined    plugin  transport   ACT qv3i1phqe1ih/1od4c6yc4wbe   hook:client,role:transport,type:web client  invalid_origin  {type:web,port:59327,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 {kind:res,res:null,error:Error: Client request timeout,sync:false,time:{client_recv:1461123692723}}
2016-04-20T03:41:32.724Z ecsaefk5ju7g/1461117713977/7376/nodezoo-npm WARN   -   -   ACT 6rd9pow3bnk9/agc94j2db5qj   name:transport,plugin:define,role:seneca,seq:3,tag:undefined    plugin  transport   ACT v3fr5gkn06m1/1od4c6yc4wbe   hook:client,role:transport,type:web client  invalid_origin  {type:web,port:59327,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 {kind:res,res:null,error:Error: Client request timeout,sync:false,time:{client_recv:1461123692724}}


Seneca Fatal Error
==================

Message: seneca: Action cmd:load,role:entity failed: [TIMEOUT:xi4ehjtoz0u4/66rvc5rblsfz:11111<1461123687743-1461123676246:undefined].

Code: act_execute

Details: { id: 'xi4ehjtoz0u4/66rvc5rblsfz',
  gate: false,
  ungate: true,
  desc: undefined,
  cb: [Function],
  fn: [Function],
  time: { start: 1461123676246, end: 1461123687743 },
  'orig$': { [Error: [TIMEOUT:xi4ehjtoz0u4/66rvc5rblsfz:11111<1461123687743-1461123676246:undefined]] timeout: true },
  'message$': '[TIMEOUT:xi4ehjtoz0u4/66rvc5rblsfz:11111<1461123687743-1461123676246:undefined]',
  message: '[TIMEOUT:xi4ehjtoz0u4/66rvc5rblsfz:11111<1461123687743-1461123676246:undefined]',
  pattern: 'cmd:load,role:entity',
  instance: 'Seneca/2.0.0/ecsaefk5ju7g/1461117713977/7376/nodezoo-npm',
  plugin: {} }

Stack: 
    at null._onTimeout (/Users/gege/nearform/nodezoo-npm/node_modules/seneca/node_modules/gate-executor/gate-executor.js:112:21)
    at Timer.listOnTimeout (timers.js:92:15)

Instance: Seneca/2.0.0/ecsaefk5ju7g/1461117713977/7376/nodezoo-npm
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/Users/gege/nearform/nodezoo-npm/node_modules/seneca/seneca.js:1220:29)

When: 2016-04-20T03:41:27.772Z

Log: [sys,seneca,2.0.0,ecsaefk5ju7g/1461117713977/7376/nodezoo-npm,act_execute,seneca: Action cmd:load,role:entity f

Node:
  { http_parser: '2.5.2', node: '4.4.1', v8: '4.5.103.35', uv: '1.8.0', zlib: '1.2.8', ares: '1.10.1-DEV', icu: '56.1', modules: '46', openssl: '1.0.2g' },
  { debug: false, uv: true, ipv6: true, tls_npn: true, tls_sni: true, tls_ocsp: true, tls: true },
  [ 'Binding contextify', 'Binding natives', 'NativeModule events', 'NativeModule buffer', 'Binding buffer', 'NativeModule internal/util', 'Binding util', 'NativeModule timers', 'Binding timer_wrap', 'NativeModule _linklist', 'NativeModule assert', 'NativeModule util', 'Binding uv', 'NativeModule child_process', 'NativeModule constants', 'Binding constants', 'Binding spawn_sync', 'Binding pipe_wrap', 'NativeModule internal/child_process', 'NativeModule string_decoder', 'NativeModule net', 'NativeModule stream', 'NativeModule _stream_readable', 'NativeModule _stream_writable', 'NativeModule _stream_duplex', 'NativeModule _stream_transform', 'NativeModule _stream_passthrough', 'NativeModule internal/net', 'Binding cares_wrap', 'Binding tty_wrap', 'Binding tcp_wrap', 'Binding stream_wrap', 'NativeModule dgram', 'Binding udp_wrap', 'Binding process_wrap', 'NativeModule internal/socket_list', 'NativeModule path', 'NativeModule module', 'NativeModule internal/module', 'NativeModule vm', 'NativeModule fs', 'Binding fs', 'Binding fs_event_wrap', 'NativeModule os', 'Binding os', 'NativeModule tty', 'NativeModule readline', 'Binding signal_wrap', 'NativeModule url', 'NativeModule punycode', 'NativeModule querystring', 'NativeModule crypto', 'Binding crypto', 'NativeModule internal/streams/lazy_transform', 'NativeModule http', 'NativeModule _http_incoming', 'NativeModule _http_common', 'NativeModule internal/freelist', 'Binding http_parser', 'NativeModule _http_outgoing', 'NativeModule _http_server', 'NativeModule _http_agent', 'NativeModule _http_client', 'NativeModule https', 'NativeModule tls', 'NativeModule _tls_common', 'NativeModule _tls_wrap', 'NativeModule _stream_wrap', 'Binding js_stream', 'Binding tls_wrap', 'NativeModule _tls_legacy', 'NativeModule zlib', 'Binding zlib', 'NativeModule dns', 'NativeModule console', 'NativeModule repl', 'NativeModule domain', 'NativeModule cluster', 'NativeModule internal/cluster' ]

Process: 
  pid=7376, arch=x64, platform=darwin,
  path=/Users/gege/.nvm/versions/node/v4.4.1/bin/node,
  argv=[ '/Users/gege/.nvm/versions/node/v4.4.1/bin/node',  '/Users/gege/nearform/nodezoo-npm/srv/start.js' ],
  env={ nodezoo_npm_queue_PORT: '10006',  nodezoo_github_PORT: '10004',  nodezoo_npm_PORT: '10003',  elastic_search_PORT_9200: '9200',  SERVICE_PORT: '20003',  nodezoo_npm_dequeue_PORT: '10007',  redis_PORT: '6379',  elastic_search_PORT_9300: '9200',  PROXY_HOST: '127.0.0.1',  nodezoo_travis_PORT: '10005',  nodezoo_base_PORT: '10000',  SERVICE_HOST: '0.0.0.0',  UPDATER_LIMIT: '4000',  GITHUB_TOKEN: 'f2c56d03f8652f282658cfb5c8cb0409f0fa2fb3',  nodezoo_web_PORT: '8000',  nodezoo_search_PORT: '10002',  nodezoo_info_PORT: '10001',  MANPATH: '/Users/gege/.nvm/versions/node/v4.4.1/share/man:/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man',  TERM_PROGRAM: 'iTerm.app',  NVM_CD_FLAGS: '',  TERM: 'xterm-256color',  SHELL: '/bin/bash',  TMPDIR: '/var/folders/cl/vzm9v8gx7w57_h2xghl20j740000gn/T/',  Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.1m0Nh31iyW/Render',  NVM_PATH: '/Users/gege/.nvm/versions/node/v4.4.1/lib/node',  DOCKER_HOST: 'tcp://172.16.183.130:2376',  USER: 'gege',  NVM_DIR: '/Users/gege/.nvm',  COMMAND_MODE: 'unix2003',  DOCKER_MACHINE_NAME: 'default',  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.ydWN7ybx1e/Listeners',  __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',  DOCKER_TLS_VERIFY: '1',  PATH: '/Users/gege/.nvm/versions/node/v4.4.1/lib/node_modules/fuge/node_modules/.bin:/Users/gege/.nvm/versions/node/v4.4.1/lib/node_modules/fuge/node_modules/.bin:/Users/gege/.nvm/versions/node/v4.4.1/bin:/Users/gege/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',  _: '/Users/gege/.nvm/versions/node/v4.4.1/bin/fuge',  NVM_NODEJS_ORG_MIRROR: 'https://nodejs.org/dist',  PWD: '/Users/gege/nearform/nodezoo-npm',  LANG: 'en_US.UTF-8',  ITERM_PROFILE: 'Default',  XPC_FLAGS: '0x0',  XPC_SERVICE_NAME: '0',  HOME: '/Users/gege',  SHLVL: '1',  DOCKER_CERT_PATH: '/Users/gege/.docker/machine/machines/default',  ITERM_SESSION_ID: 'w0t0p1:1659AD32-5A8D-4F5B-BBFC-F5C8FF44A1B6',  LOGNAME: 'gege',  NVM_BIN: '/Users/gege/.nvm/versions/node/v4.4.1/bin',  NVM_IOJS_ORG_MIRROR: 'https://iojs.org/dist',  SECURITYSESSIONID: '186a7' }




SENECA TERMINATED at 2016-04-20T03:41:32.978Z. See above for error report.

```

**Comment by mcdonnelldean** [comment]
@mirceaalexandru This might be related to #7

**Comment by mirceaalexandru** [comment]
Fixed by
https://github.com/nodezoo/nodezoo-updater/commit/4c9a4950a84cc8744d10d065cd811621c5de87d0

That is a hack until redis queue will have a way to control the concurrency level of message processing.
