### ISSUE TITLE
Attempting to setup nodezoo-system on fuge, and have received the following error: `Ready check failed: NOAUTH Authentication required.`

### ISSUE THREAD

**Issue by GlenTiki** [nodezoo/nodezoo-dequeue#8]
Here is the relevant stack trace which I have received:

```
[nodezoo_dequeue - 70314]: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Ready check failed: NOAUTH Authentication required.
    at JavascriptReplyParser.parseResult (/Users/glen/work/nearform/nodezoo-system/services/nodezoo-dequeue/node_modules/redis-parser/lib/javascript.js:90:16)
    at JavascriptReplyParser.tryParsing (/Users/glen/work/nearform/nodezoo-system/services/nodezoo-dequeue/node_modules/redis-parser/lib/javascript.js:117:21)
    at JavascriptReplyParser.run (/Users/glen/work/nearform/nodezoo-system/services/nodezoo-dequeue/node_modules/redis-parser/lib/javascript.js:131:22)
    at JavascriptReplyParser.execute (/Users/glen/work/nearform/nodezoo-system/services/nodezoo-dequeue/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/Users/glen/work/nearform/nodezoo-system/services/nodezoo-dequeue/node_modules/redis/index.js:223:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
process exit [70314]: nodezoo_dequeue
```

**Comment by Georgette** [comment]
This looks like a redis issue...as if someone is setting a password somehow. I know it was originally set up without a PW but for prod, we probably want to have one so it doesn't get fussed with.

Here, follow this thread I found on how to go about it:

 http://stackoverflow.com/questions/34115213/redis-raise-error-noauth-authentication-required-but-there-is-no-password-setti

**Comment by mcdonnelldean** [comment]
Awesome stuff @Georgette @mirceaalexandru nodezoo-system would need to be updated too with some envs.

**Comment by mirceaalexandru** [comment]
Yes, and also we need some env vars for base host - as an example. This is required when installing on different machines.
